# Generated by Django 3.2 on 2023-02-19 11:43

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMaster',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('thumbnailimage', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image1', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image2', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image3', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image4', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image5', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image6', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image7', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
                ('image8', models.ImageField(blank=True, help_text='Maximum file size allowed is 4Mb', null=True, upload_to='uploads/', validators=[home.models.validate_image])),
            ],
            options={
                'db_table': 'PORTFOLIOMASTER',
            },
        ),
    ]
