# Generated by Django 3.2 on 2023-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfoliomaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
