# Generated by Django 3.2 on 2023-02-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_portfoliomaster_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfoliomaster',
            table=None,
        ),
    ]
