# Generated by Django 3.2 on 2023-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230221_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomaster',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Print', 'Print'), ('Packaging', 'Packaging'), ('Illustration', 'Illustration'), ('Digital', 'Digital'), ('Branding', 'Branding')], default='all', max_length=15),
        ),
    ]
